[package]
name = "asset-hub-polkadot-integration-tests"
version = "1.0.0"
authors.workspace = true
edition.workspace = true
license = "Apache-2.0"
description = "Asset Hub Polkadot runtime integration tests with xcm-emulator"
publish = false

[dependencies]
codec = { package = "parity-scale-codec", version = "3.6.9" }

# Substrate
sp-runtime = { version = "30.0.1" }
frame-support = { version = "27.0.0" }
frame-system = { version = "27.0.0" }
pallet-assets = { version = "28.0.0" }
pallet-balances = { version = "27.0.0" }
pallet-asset-conversion = { version = "9.0.0" }

# Polkadot
polkadot-core-primitives = { version = "6.0.0" }
polkadot-parachain-primitives = { version = "5.0.0" }
polkadot-runtime-parachains = { version = "6.0.0" }
xcm = { package = "staging-xcm", version = "6.0.0" }
pallet-xcm = { version = "6.0.0" }

# Cumulus
parachains-common = { version = "6.0.0" }
xcm-emulator = { version = "0.4.0" }

# Local
integration-tests-common = { path = "../../common" }

[features]
runtime-benchmarks = [
    "integration-tests-common/runtime-benchmarks"
]
