[package]
name = "chain-spec-generator"
version.workspace = true
authors.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
clap = { version = "4.4.4", features = [ "derive" ] }
hex-literal = "0.4.1"
serde_json = "1.0.107"

polkadot-runtime = { path = "../relay/polkadot" }
polkadot-runtime-constants = { path = "../relay/polkadot/constants" }
kusama-runtime = { package = "staging-kusama-runtime", path = "../relay/kusama" }
kusama-runtime-constants = { path = "../relay/kusama/constants" }

sc-chain-spec = "24.0.0"
polkadot-runtime-parachains = "4.0.0"
polkadot-primitives = "4.0.0"
sp-consensus-babe = "0.29.0"
sp-authority-discovery = "23.0.0"
sp-core = "25.0.0"
pallet-staking = "25.0.0"
sc-consensus-grandpa = "0.16.0"
pallet-im-online = "24.0.0"
sp-runtime = "28.0.0"
sp-consensus-beefy = "10.0.0"

[features]
runtime-benchmarks = [
	"kusama-runtime/runtime-benchmarks",
	"polkadot-runtime/runtime-benchmarks",
]
